### ISSUE TITLE
serde_derive brings binary blob and breaks builds

### ISSUE THREAD

**Issue by pinkforest** [chronotope/chrono#1218]
serde_derive has chosen interesting approach
- https://github.com/serde-rs/serde/issues/2538

I've sent PR to make the binary blob opt-in approach so the top-level binary chooses the desired build / trust model instead

This breaks Nix builds etc so I would recommend restricting the SemVer scope on serde_derive for dev-dep and serde for dep

It was labeled as "Experimental" to embed the binary blob but it went straight to prod :(

```toml
[dependencies]
serde = { version = "1.0.99, <= 1.0.171", optional = true, default-features = false }
```

The above should also restrict the serde_derive on dev-dependencies to that range.
