### ISSUE TITLE
format paniced

### ISSUE THREAD

**Issue by fengyangsi** [chronotope/chrono#1363]
I use chrono to translate timestamp to ISO format string in wasm program. And panic when call format function.

There was code

```rust
use worker::*;
use chrono::NaiveDateTime;

#[event(fetch)]
async fn main(req: Request, env: Env, ctx: Context) -> Result<Response> {
    panic::set_hook(Box::new(|_| {
        worker::console_error!("panic!");
    }));
    // this line didn't panic
    let now = NaiveDateTime::from_timestamp_millis(Date::now().as_millis() as i64).unwrap();
    // this line panic - format function
    Response::ok(now.format("%Y-%m-%dT%H:%M:%S%.f%:z").to_string())
}
```

```rust
    //panic
    now.format("%Y-%m-%dT%H:%M:%S%.f%:z")
    //also panic
    now.format("%+")
```

Cargo.toml
```toml
# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.31"
worker = "0.0.18"

[profile.release]
lto = true
strip = true
codegen-units = 1
```

wrangler.toml
```toml
main = "build/worker/shim.mjs"
compatibility_date = "2023-11-20"

[build]
command = "worker-build"
#also panic when command = "worker-build --release"
```
