### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by quodlibetor** [chronotope/chrono#336]
mentioned in [195](https://github.com/chronotope/chrono/issues/195#issuecomment-527201627), we need a good story around no_std/alloc support.

The parts of this that jump right to mind:

* Breaking up the core mathy parts of chrono into their own crates/features
* Refactoring various stringy bits to be in terms of `Write`
* parts of chrono around parsing allocate, too, I believe.

**Comment by quodlibetor** [comment]
Honestly I'm not sure how far Chrono is from supporting no_std when the default features are turned off. I think some people might already be using it semi-successfully? Code that people would like to work, but does not, would be welcome.

For example, this seems to work:

```rust
#![no_std]

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        use chrono::TimeZone;
        let _ = chrono::Utc.ymd(1999, 1,1).and_hms(1, 2, 3);
    }
}
```

**Comment by alex** [comment]
My understanding is that testing `#![no_std]` with `cargo test` doesn't necessarily prove what you expect, because `libtest` links `std`.

**Comment by quodlibetor** [comment]
that makes sense, this also works, though:
```toml
# Cargo.toml
[package]
name = "nostd"
version = "0.1.0"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", default-features = false }
```
```rust
// src/lib.rs
#![no_std]

use chrono::TimeZone;

pub fn dt() -> chrono::DateTime<chrono::Utc> {
    chrono::Utc.ymd(1999, 1,1).and_hms(1, 2, 3)
}
```
```bash session
$ cargo build
   Compiling nostd v0.1.0 (/Users/bwm/github/chrono/examples/nostd)
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
```
